name = "ens"
main = "src/index.ts"
compatibility_date = "2023-03-15"

kv_namespaces = [
  { binding = "RECORDS", id = "92d3c483ac9741b49b1de47751248ab1", preview_id = "176b9d2f873d4af282d93c0e94da8e42" },
]

[vars]
IS_TEMPORARY=true

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
